fragment PlatformInfo on DataPlatform {
  properties {
    displayName
    logoUrl
  }
}

fragment TermsInfo on GlossaryTerms {
  terms {
    term {
      properties {
        name
      }
    }
  }
}

fragment OwnershipInfo on Ownership {
  owners {
    owner {
      ... on CorpUser {
        properties {
          displayName
        }
      }
      ... on CorpGroup {
        properties {
          displayName
        }
      }
    }
  }
}

fragment DomainInfo on DomainAssociation {
  domain {
    properties {
      name
    }
  }
}

fragment EntitySocialDetails on Entity {
  urn
  type
  ... on Dataset {
    properties {
      name
      description
    }
    editableProperties {
      description
    }
    platform {
      ...PlatformInfo
    }
    subTypes {
      typeNames
    }
    glossaryTerms {
      ...TermsInfo
    }
    ownership {
      ...OwnershipInfo
    }
    domain {
      ...DomainInfo
    }
  }
  ... on Chart {
    properties {
      name
      description
    }
    editableProperties {
      description
    }
    platform {
      ...PlatformInfo
    }
    glossaryTerms {
      ...TermsInfo
    }
    ownership {
      ...OwnershipInfo
    }
    domain {
      ...DomainInfo
    }
  }
  ... on Dashboard {
    properties {
      name
      description
    }
    editableProperties {
      description
    }
    platform {
      ...PlatformInfo
    }
    glossaryTerms {
      ...TermsInfo
    }
    ownership {
      ...OwnershipInfo
    }
    domain {
      ...DomainInfo
    }
  }
  ... on Tag {
    properties {
      name
      description
    }
    ownership {
      ...OwnershipInfo
    }
  }
}
